# GitHub Actions Components
#- Workflow: A configurable automated process made up of one or more jobs.
#- Event: A specific activity that triggers a workflow to run.
#- Job: A set of steps that execute on the same runner.
#- Step: An individual task that can run commands or use an action.
#- Action: A reusable extension that can be used in workflows to perform a specific task.
#- Runner: A server that runs your workflows when they are triggered.

name: My first workflow 

# Trigger the workflow on push to main branch
on: 
    push:
        branches:
            - main

# Define the job to run
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Let other actions access the repository code
            - name: Checkout repository
              uses: actions/checkout@v4


            - name: Say Hello
              run: |
                echo "Hello, World! from GitHub Actions  Repository: ${{ github.repository }} Branch: ${{ github.ref }} Actor: ${{ github.actor }}"






